Repository Clinical-Genomics/demultiplexing, pull requests merged in 2021-02, with the labels that each got.

#137 fix novaseq demux script to enable automated post demux actions
  scripts/novaseq/checkfornewrun.bash
  scripts/novaseq/stage/checkfornewrun.bash
Labels: Effort S, Gain L, Urgency L, demux migration

#138 fix(novaseq_bind_path): Reduce the bind path to simply it and remove …
  scripts/novaseq/demux-novaseq.sh
  scripts/novaseq/stage/demux-novaseq.sh
Labels: bug

#142 Fix/lane count novaseq
  .idea/.gitignore
  .idea/aws.xml
  .idea/demultiplexing.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  demux/constants/indexreport.py
  demux/utils/indexreport.py
  tests/utils/conftest.py
  tests/utils/test_indexreport.py
Labels: Effort S, Gain L, Urgency M, bug
